export const data_properties = [
    {
      id: 1,
      title: "Luxury Villa N1_36 in Folie Village, Jale Beach",
      description: "This luxurious two-story villa in Jale offers an exceptional blend of modern design and breathtaking panoramic views of the bay. Spanning a total net living surface of 450 m², the villa is designed for elegance and comfort. The ground floor covers 189 m², the first floor 173 m², and the second floor 88 m², ensuring spacious interiors flooded with natural light. Outdoor living is just as impressive, featuring an 85.8 m² veranda, a large 48 m² private pool, and a beautifully landscaped garden on a 403 m² parcel. Designed for those seeking privacy and exclusivity, this home is perfect for relaxation and entertainment. The villa is set to be completed by May 2026, and is available at €3,500 per square meter, making it a prime investment opportunity in one of Albania’s most stunning coastal locations.",
      price: "3500 €/m²",
      bedrooms: 3,
      bathrooms: 4,
      m2: 450,
      address: "Jale Beach, Albania",
      images: ["/images/FM_outside_villa.png",
       "/images/folie_marine_masterplan.png",
        "/images/folie_marine_village.png",
        "/images/FM_inside_villa.png",
        "/images/FM_garden_villa.png",
        "/images/FM_ground_floor.png",
        "/images/FM_first_floor.png",
        "/images/FM_first_floor_2.png",
        "/images/FM_second_floor.png",
        "/images/FM_p_ballore1.png",
        "/images/FM_p_ballore2.png",
        "/images/FM_fasada_jugore.png"
      ],
      featured: true
    },
    {
      id: 2,
      title: "Modern Apartments in the heart of Tirana city",
      description: "This modern residential and service building is currently under construction in Tirana, located on Mahmut Fortuzi and Vildan Luarasi streets. The development features 5, 6, 7, 8, and 9 floors above ground, along with 2 underground parking levels, offering a perfect blend of residential comfort and commercial functionality. Designed with contemporary architecture and high-quality materials, this building provides a prime investment opportunity in one of Tirana’s most sought-after locations. We offer various apartments for sale, including 1+1, 2+1, and luxurious penthouse units,starting at a price of €2,500 per square meter. Additionally, commercial spaces are available starting at €3,300 per square meter, making this an ideal opportunity for both homeowners and business investors. Whether you’re looking for a cozy apartment or a commercial space in a prime urban area, this development offers elegance, convenience, and modern city living.",
      price: "2500 - 3300 €/m²",
      bedrooms: null,
      bathrooms: null,
      m2: null,
      address: "Mahmut Fortuzi & Vilden Luarasi, Tirane",
      images: ["/images/pallati.jpeg",
         "/images/planimetri_kati1.png",
         "/images/planimetri_kati2.png",
         "/images/planimetri_kati3.png",
         "/images/planimetri_kati4.png",
         "/images/planimetri_kati5.png",
         "/images/planimetri_kati6.png",
         "/images/planimetri_kati7.png",
         "/images/planimetri_kati8.png",
        ],
      featured: true
    },
    {
      id: 3,
      title: "Modern 1+1 Apartment for Sale in Tirana’s Dry Lake",
      description: "Located in one of Tirana’s most desirable neighborhoods, this modern 1+1 apartment offers a spacious and stylish living environment. Featuring a cool-toned interior, the apartment is perfect for a small family looking for comfort and functionality. It includes one bedroom, one bathroom, an open-plan living room with a kitchen, and a cozy balcony. Fully furnished and designed for a warm, inviting atmosphere, this apartment provides a perfect blend of modern aesthetics and homey comfort.",
      price: "200000 €",
      bedrooms: 1,
      bathrooms: 1,
      m2: null,
      address: "Tirana’s Dry Lake",
      images: ["/images/3.jpg",
         "/images/2.jpg",
         "/images/1.jpg",
         "/images/4.jpg",
         "/images/d1.jpg",
         "/images/d2.jpg",
         "/images/veranda.jpg",
         "/images/v2.jpg",
        ],
      featured: true
    },
    {
      id: 4,
      title: "Modern 1+1 Apartment for Sale in Korce",
      description: "Located in the center of Korça, right next to Themistokli Germenji High School, this charming 40 m² apartment offers an ideal living space. Situated on the sixth floor of a residential building, it is close to a beautiful park and just steps away from the Old Bazaar, one of the city's most iconic attractions.This newly renovated 1+1 apartment has been fully furnished with modern investments in recent years and comes with full property ownership documentation (tapi). The building has the potential for an elevator installation, with full agreement from all residents.",
      price: "52000 €",
      bedrooms: 1,
      bathrooms: 1,
      m2: 40,
      address: "Bulevard Fan Noli, Korce, Albania",
      images: ["/images/Korce-Albania.jpg",
        "/images/pazari_korce.jpg"],
      featured: true
    },
    {
      id: 5,
      title: "Parcel for sale at Gjeneral's Beach, Kavaje",
      description: "",
       price: "60€/m²",
      bedrooms: null,
      bathrooms: null,
      m2: null,
      address: "Gjeneral's Beach, Kavaje, Albania",
      images: ["/images/plazhi_gjeneralit_1.png",
        "/images/plazhi_gjeneralit_2.png",
      "/images/plazh_gjen.jpg"],

      featured: true
    },
    {
      id: 6,
      title: "Parcel for sale at Kallm, Durres       ",
      description: "",
      price: "50€/m²",
      bedrooms: null,
      bathrooms: null,
      m2: null,
      address: "Kallm, Durres, Albania",
      images: ["/images/kallm-beach.jpg",
        "/images/durres-beach-kallmi-bukur-1.jpg",
      "/images/kallmi_beach.jpg"],
      featured: true
    },
    {
      id: 7,
      title: "Parcel for sale at Cape of Rodon, Durres",
      description: "",
      price: "15000000€",
      bedrooms: null,
      bathrooms: null,
      m2: 250000,
      address: "Cape of Rodon, Durres, Albania",
      images: ["/images/cape_rodon.jpg",
        "/images/rodon.jpg",
        "/images/Cape_of_Rodon.png"],
      featured: true
    },
    {
      id: 8,
      title: "Parcel for sale at Cape of Rodon, Durres",
      description: "",
      price: "10200000€",
      bedrooms: null,
      bathrooms: null,
      m2: 170000,
      address: "Cape of Rodon, Durres, Albania",
      images: ["/images/cape_rodon.jpg",
        "/images/rodon.jpg",
        "/images/Cape_of_Rodon.png"],
      featured: true
    },
    {
      id: 9,
      title: "Parcel for sale at Cape of Rodon, Durres",
      description: "",
      price: "6000000€",
      bedrooms: null,
      bathrooms: null,
      m2: 100000,
      address: "Cape of Rodon, Durres, Albania",
      images: ["/images/cape_rodon.jpg",
        "/images/rodon.jpg",
        "/images/Cape_of_Rodon.png"],
      featured: true
    }
    ,
    {
      id: 10,
      title: "Parcel for sale at Karaburun Peninsula, Vlore",
      description: "",
      price: "12000000€",
      bedrooms: null,
      bathrooms: null,
      m2: 240000,
      address: "Karaburun Peninsula, Vlore, Albania",
      images: ["/images/karaburunt_bay.jpg",
        "/images/Karaburun-Peninsula-Albania-scaled.jpg",
        "/images/karaburun-11.jpg",
        "/images/Karaburun-penisula-Albania-819x1024.jpg",
        "/images/karaburunt_peninsula.jpg"      ],
      featured: true
    }
  ];
  
  export const agents = [
    {
      id: 1,
      name: "John Smith",
      title: "Senior Agent",
      bio: "15 years of experience",
      image: "agent1.jpg",
      email: "john@example.com",
      phone: "123-456-7890"
    }
  ];